project: 
  type: website
  
website: 
  page-navigation: true
  title: "Combocat" 
  site-url: "https://combocat.stjude.org" 
  repo-url: https://github.com/wcwr/combocat 
  repo-actions: [issue]
  
  page-footer:
    right: ":star: This doc's code is on [GitHub](https://github.com/wcwr/combocat/tree/main/docs)."
    left: "Charlie Wright, 2024"
    
  sidebar:
    logo: "images/cat_sidebar.svg"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://combocat.stjude.org
        text: "combocat.stjude.org"
      - icon: github
        href: https://github.com/wcwr/combocat
        text: "Combocat GitHub"
      - icon: twitter
        href: https://twitter.com/biowright
        text: "Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - background.qmd
      - section: Experimental setup
        contents: 
          - href: experimental_landing.qmd
            text: Overview
          - experimental_dense_mode.qmd
          - experimental_sparse_mode.qmd
      - href: transition-from-rmarkdown.qmd
      - section: Analysis
        contents:
          - analysis_landing.qmd
          - analysis_dense_mode.qmd
          - analysis_sparse_mode.qmd
      - href: machine_learning.qmd
      - href: advanced.qmd


format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
