---
title: Experimental overview
from: markdown+emoji <!--# allows emojis #-->
---

Running a Combocat experiment is pretty straightforward. It can loosely be thought of as design ➝ execute ➝ analyze.

The documentation here provides information on all steps.

## Required Materials

Regardless of your experiment setup, you'll need some materials and access to instruments.

::: {.callout-note}
This documentation focuses on the luminescence-based [CTG assay](https://www.promega.com/-/media/files/resources/protocols/technical-bulletins/0/celltiter-glo-luminescent-cell-viability-assay-protocol.pdf?rev=30e8ec640fdd4866b207e28c0cbc497c&sc_lang=en). \
Combocat is generalizable to the readout of your choice (e.g., imaging, fluorescence, etc). Swap out materials accordingly.
:::

-   [**Microwell plates**]{.underline}

    -   384-well for dense mode, 1536-well for sparse mode (suitable for cell culture)

    -   [Echo-compatible plates](https://www.mybeckman.co/supplies/echo-qualified-supplies/acoustic-liquid-handler-microplates/001-14555) (if using an Echo acoustic liquid handler)

-   [**Desired drugs**]{.underline}

    -   Soluble at 400X final desired top concentration

-   [**Control compounds**]{.underline}

    -   Positive control for cell death (i.e., Staurosporine for mammalian cells)

    -   Vehicle control for drug solvents (i.e., DMSO)

-   **Desired cells**

-   **CTG reagents**

-   [**Access to instruments**]{.underline}

    -   Echo (or other well-to-well acoustic liquid handler)

    -   Luminometer (or instrument specific to assay readout)

    -   Incubator

    -   Centrifuge capable of spinning microplates

    -   (Optional) liquid handler for cell/reagent dispensing

## Key considerations

It's important to verify that your assay conditions are working before starting the experiment. For example:

-   Ensure volumes of drug stocks are sufficient for assay scale (see protocols)

-   Optimize cell seeding densities

-   Verify calibration of instruments
