---
title: "Combocat"
subtitle: "Scalable and interpretable drug combination screening"
from: markdown+emoji <!--# allows emojis #-->
author:
  - name: "Charlie Wright"
    email: "charlie.wright@stjude.org"
---

## Welcome {#welcome}

This is the documentation for Combocat, a start-to-finish platform for drug combination screening. 

Combocat is fully open-source!:tada:

In this documentation, you will find steps to complete both **experimental** and **analytical** parts of Combocat experiments. The experimental sections include step-by-step protocols with examples. In the data analysis sections, we provide steps for processing and analyzing results using the `combocat` R package. Browse links in the sidebar to the left to find out information about each step. 

## Overview

Quarto helps you have your ideas and your code in one place, and present it in a beautiful way. 

**Quarto unifies and extends the RMarkdown ecosystem** - it unifies by combining the functionality of R Markdown, bookdown, distill, xaringian, etc into a single consistent system. And it extends in several ways: all features are possible beyond R too, including Python and Javascript. It also has more “guardrails”: accessibility and inclusion are centered in the design. Quarto is for people who love RMarkdown, and it's for people who have never used RMarkdown. 
 

## Reference

[Openscapes](https://openscapes.org) is about better science for future us. We help researchers reimagine data analysis, develop modern skills that are of immediate value to them, and cultivate collaborative and inclusive research teams as part of the broader global open movement.

We're developing this tutorial to help folks with different levels of technical skills use [Quarto](https://quarto.org) for documentation and tutorial building. This tutorial was originally created for several different audiences: [NASA-Openscapes](https://nasa-openscapes.github.io) researcher support engineers using Python, communications directors at organizations promoting open science who do not identify as coders, and fisheries scientists curious about transitioning from RMarkdown. We're hoping it's useful to folks with backgrounds as wide as these; if you find it useful or have suggestions for improvement, please let us know by clicking "Edit this page" or "Report an issue" at the upper right side of any page.
